### ISSUE TITLE
Task1 question

### ISSUE THREAD

**Issue by shihe407** [fkong7/HeartDeformNets#1]
How to get files in task1_mmwhs.yaml , names are: 09_13_2022_22_29_27_bbw.dat & 09_13_2022_22_29_27_template.vtp
I want to run task1 to get heart segmentation. 
When i change the seg_fn in create_template.sh，then run the source create_template.sh, there are some errors such as :

‘’Segmentation fault (core dumped)
Reading volume mesh information...
Reading interpolated mesh information...
Computed bary centers...
Segmentation fault (core dumped)‘’

Do u know how to solve this？
If u can provide those two files, might can be help？
Thanks for your reading.

**Comment by shihe407** [comment]
when run 'source create_template.sh' ,get some warnings like
 " [        C6ECF740]            vtkMath.cxx:596   WARN| Unable to factor linear system "

**Comment by fkong7** [comment]
You shouldn't need to change seg_fn, unless you are running it on your own segmentation. And in that case, please make sure the format and data type you are using is consistent with the example.

The warning message is from mesh decimation and can be ignored.

I'm closing this since it's been awhile but please feel free to reopen if issues persist.
